use reason;

INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Philip", "abri123", "11");
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Mo","iko123","12", "11");
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Lavern","vern123", "10");
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Bryan", "brave123", "12");
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Dania", "dan123", "10");
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Kisha", "cord123", "12");
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Lani", "shame123", "11);
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Jimmie", "phew123", "9");
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Nathanial", "gill123", "10");
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Chaya", "chay123", "11");
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Troy", "boy123", "10";
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Tana","ese123", "11");
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Zachery","pop123", "11");
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Dario","acre123", "10");
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Candie", "bass123", "12");
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Sherita", "sord123", "10);
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Holli", "zeit123", "11);
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Alyson", "foll123", "9");
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Margrett", "ghee123", "9");
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Ching","get123", "12"));
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Roman","allin123", "11"));
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Hui","puz123", "10");
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Truman","rite123", "11");
INSERT INTO users(`first_name`, `user_name`, `school_year, date_registered`) VALUES ("Margarite","bug123", "11");

INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("5", "e","Within each row the figure turns 45 degrees clockwise with every step to the right." );
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("5","c","Within each row, the arrow rotates 135 degrees clockwise with each step to the right.");
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("4","a",);
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("4","b", "The figure with the dots moves a quarter turn counterclockwise each step down. In addition, the number of dots on the figure doubles every step to the right. The figure in the answer should contain 16 dots and be at the top left.");
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("3","b", );
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("3","c","For each column contains different figures, the middle one contains circles. From top to bottom, the number of figures increases by 2 each step. In addition, the figure moves to the other corner each step down. The answer must contain three circles in the top right corner." );
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("5","b",);
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("3","b","Each column (vertical) contains two figures with a sharp angle and 1 figure with an obtuse angle. In addition, the inner figure rotates 90 degrees counterclockwise the first step and 180 degrees the next step.\n\nThe answer must contain an outer figure with sharp angles and an inner figure with the ends pointing down." );
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("4","e",);
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("3","d",);
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("4","b",);
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("5","e",);
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("6","a",);
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("3","d", );
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("4","d",);
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("3","e", );
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("5","b",);
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("5","e",);
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("3","c",);
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("3","c", );
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("3","b", );
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("5","f",);
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("5","e",);
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("4","f",);
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("6","b",);
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("6","c", );
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("5","b", );
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("5","c",);
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("3","c", );
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("3","c",);
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("7","d", "The nine cells in the grid make a symmetric shape." );
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("7","b","The figures in the first column grow in size each step to the right. "  );
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("7","c", "The width of the figures in the first column shrink in size each step to the right. ");
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("7", "a","The figures in the first and second column are merged in the third column");
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("7","d", "The figures in the first and second column are merged in the third column." );
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("6", "a", "The black circle moves up each column, the white square moves to the right each column. Every row the placement of the white square is different" );
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("6","b","The figures move counter clockwise from corner to corner every column. A triangle is followed by a square, a square is followed by a circle and a circle is followed by a triangle" );
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("6","a", "The arrow rotates clockwise every column, first 45 degrees, then 180 degrees. The figures move counter clockwise from corner to corner every column. A circle is followed by a square, a square is followed by a triangle and a triangle is followed by a circle"  },);
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("6","c", "Every row is a calculation. The number of black circles outside a figure represent a positive number, the number of black circles within a figure represent a negative number. The third column is the sum of the first and second column. Every row has the same three figures. A square is followed by a triangle, a triangle is followed by a circle and a circle is followed by a square."  },);
INSERT INTO questions(`difficulty_rating`, `question_url`,`answer_url`, `answer`, `additional_instructions`, `explanation`, `date_added`) VALUES ("6", "b","Every column the circle moves to the right and changes from white to black and vice versa. Every row the circle moves down. Every column the square moves to the left and changes from black to white and vice versa. Every row the square moves up. Every column the horizontal line moves up." );

